### ISSUE TITLE
Create application class

### ISSUE THREAD

**Issue by sOM2H** [MarkPater/TNC#1]
I believe that you need to transfer the logic from main.cpp to tnc.cpp, so that from main.cpp you only manage the state of the application. I think it will be better) What do you think?

Example: main.cpp
```
#include "tnc.hpp"

int main(void){
	Tnc* Tnc = new Tnc();
	tnc->init();
	while(tnc->running){
		tnc->handle_events();
		tnc->update();
		tnc->render();
	}
	tnc->close();
}
```

In tnc.hpp you may declare all global variables and include all libraries what you need.
In tnc.cpp you may to realize main functions as instance methods.
Generally, I'm waiting for your opinion)

**Comment by MarkPater** [comment]
Thank you for your task. This idea just suitable for my project and I will try do it in the next time.
